# EdgeOne kafka Docker build pipeline 
# Example: germanedge-docker/kafka:latest
# dockerRegistry: "artifactory.new-solutions.com" -> image container registry service

name: "e1-kafka_$(Date:yyyyMMdd)$(Rev:.r)"

variables:
  dockerId: "edge-one"  # Docker-ID for container registry service
  artifactRegistry: "germanedge-docker.artifactory"
  imageName: "kafka"

trigger:
- master
- develop

pr: none

jobs:

- job: 'DockerLinuxmaster'
  condition: eq(variables['build.SourceBranchName'], 'master')
  displayName: 'creates a kafka Docker image for Linux for master'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: 'Build and Push the image'
    inputs:
      containerRegistry: '$(artifactRegistry)'
      repository: '$(dockerId)/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest
        master

- job: 'CreateDockerKafka_Linuxdev'
  condition: eq(variables['build.SourceBranchName'], 'develop')
  displayName: 'creates a Docker image linux - dev branch'
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: 'Build and Push the image (Linux)'
    inputs:
      containerRegistry: '$(artifactRegistry)'
      repository: '$(dockerId)/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest
        develop