# EdgeOne kafka Docker build pipeline 
# Example: germanedge-docker/kafka:latest
# dockerRegistry: "artifactory.new-solutions.com" -> image container registry service

variables:
  dockerId: "edge-one"  # Docker-ID for container registry service
  artifactRegistry: "germanedge-docker.artifactory" # artifactory path
  imageName: "kafka"  
  artifactoryURL: "germanedge-docker.artifactory.new-solutions.com"

name: "$(imageName) $(GitVersion.FullSemVer)"

resources:
  repositories:
    - repository: templates
      type: github
      name: Germanedge/azure-pipelines-templates
      endpoint: Germanedge

extends:
  template: azure-pipelines-docker-template.yml@templates