apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: edgeone
spec:
  selector:
    app: kafka
  type: ClusterIP
  ports:
  - targetPort: 9092
    port: 9092
    name: port0
  - targetPort: 7071
    port: 7071
    name: port1
