---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chtest-kafka2-pv-claim
  namespace: chtest
spec:
  storageClassName: ebs-1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4G
